CREATE TABLE data (
  id BIGSERIAL PRIMARY KEY,
  data TIMESTAMP NOT NULL,
  id_sensor SMALLINT NOT NULL,
  delta INTEGER NOT NULL,
  bateria SMALLINT NOT NULL,
  h2s DOUBLE PRECISION,
  umidade DOUBLE PRECISION,
  nh3 DOUBLE PRECISION,
  temperatura DOUBLE PRECISION,
  ocupado SMALLINT,
  sensor TEXT NOT NULL,
  registro_id BIGINT NOT NULL
);
